@relation  iris
@attribute sepallength {0,1,2,3}
@attribute sepalwidth {0,1,2,3,4}
@attribute petallength {0,1,2}
@attribute petalwidth {0,1,2}
@attribute class{Iris-setosa,Iris-versicolor,Iris-virginica}
@inputs sepallength,sepalwidth,petallength,petalwidth
@outputs class
@data
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-setosa Iris-setosa
Iris-versicolor Iris-setosa
Iris-versicolor Iris-setosa
Iris-versicolor Iris-setosa
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-setosa
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-setosa
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-setosa
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-setosa
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-setosa
Iris-versicolor Iris-setosa
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-setosa
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-setosa
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-setosa
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-setosa
Iris-versicolor Iris-setosa
Iris-versicolor Iris-setosa
Iris-versicolor Iris-setosa
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-setosa
Iris-versicolor Iris-setosa
Iris-versicolor Iris-setosa
Iris-versicolor Iris-setosa
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-setosa
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-versicolor
Iris-versicolor Iris-versicolor
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
Iris-virginica Iris-setosa
