@relation weather.symbolic
@attribute outlook{sunny,overcast,rainy}
@attribute temperature{hot,mild,cool}
@attribute humidity{high,normal}
@attribute windy{TRUE,FALSE}
@attribute play{yes,no}
@inputs outlook, temperature, humidity, windy
@outputs play
no no
no no
yes yes
yes no
yes no
no no
yes yes
no no
yes no
yes no
yes no
yes no
yes yes
no no
